name: "kolla-builder"
description: "build set of kolla containers"
inputs:
  config_set:
    description: "What platform to build for (e.g., x86_ubuntu,x86_centos,x86_centos7,aarch64_debian...) choose one."
    required: true
  kolla_build_profile:
    description: "Kolla profile(s) to build (e.g., 'base', 'ironic'), comma-separated"
    required: false
  build_pattern:
    description: "Kolla image build pattern (e.g., '^ironic-')"
    required: false
  push:
    description: "Push images to registry? (yes/no)"
    required: true
    default: no
  docker_tag:
    description: "what to tag the images with"
    required: false
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: msherman64/kolla-containers
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: execute build
      env:
        DOCKER_TAG: ${{ inputs.docker_tag }}
      run: |
        ./run.sh python3 build.py \
          --build-dir ${{ runner.temp }} \
          --no-use-cache \
          --config-set ${{ inputs.config_set }} \
          --profile ${{ inputs.kolla_build_profile }}
      shell: bash
